### ISSUE TITLE
Shell completion support

### ISSUE THREAD

**Issue by james-callahan** [drGrove/mtls-cli#35]
I should be able to tab-complete servers, configs and subcommands.

Please support zsh, bash and fish.

**Comment by james-callahan** [comment]
This appears to be built into click. https://click.palletsprojects.com/en/7.x/bashcomplete/

**Comment by drGrove** [comment]
Automatic completion creation on install is up to packaging and currently now available in [Arch Linux](https://aur.archlinux.org/cgit/aur.git/commit/?h=mtls&id=4b409bc9930ed89e990424462c7e1e7464ff349d)
